label start:
    scene black
    "Welcome to your new Ren'Py project!"
    "Generated by the Ren'Py MCP server."
    "The game will now end and return to the main menu."
    
    # IMPORTANT: Always end with 'return' to prevent looping
    return
